### ISSUE TITLE
Rotation Matrix for View configurations

### ISSUE THREAD

**Issue by YoungXIAO13** [daniilidis-group/emvn#1]
Hi Carlos,

Congrats for being accepted as ICCV Oral!
I'm wondering how to obtain the rotation matrix for the different view configurations in your paper: 12x5, 20x3, 60x1.
It would be very nice if you can share the code to generate these matrices.

**Comment by xuyinxuyin** [comment]
Hi, Here is my matlab code:
function [alter,altermatri,alterot]=alter52()
a=zeros(12,12);
a(1,7)=1;
a(2,11)=1;
a(3,12)=1;
a(4,5)=1;
a(5,4)=1;
a(6,8)=1;
a(7,1)=1;
a(8,6)=1;
a(9,10)=1;
a(10,9)=1;
a(11,2)=1;
a(12,3)=1;
blist=[2,7,6,5,10,11,1,9,12,4,3,8];
b=zeros(12,12);
for i=1:12
    b(i,blist(i))=1;
end
[Ra,Rb]=rotation();
A1=eye(12,12);
A2=a;
A3=b;
A4=b*a;
A5=b*a*b;
A6=b*a*b*a*b;
A7=b*a*b*a;
A8=b*a*b*a*b*a;
A9=b*a*b*a*b*b;
A10=b*a*b*a*b*b*a;
A11=b*a*b*a*b*b*a*b*a;
A12=b*a*b*a*b*b*a*b;
AA={A1 A2 A3 A4 A5 A6 A7 A8 A9 A10 A11 A12};
c=a*b;

AR1=eye(3,3);
AR2=Ra;
AR3=Rb;
AR4=Rb*Ra;
AR5=Rb*Ra*Rb;
AR6=Rb*Ra*Rb*Ra*Rb;
AR7=Rb*Ra*Rb*Ra;
AR8=Rb*Ra*Rb*Ra*Rb*Ra;
AR9=Rb*Ra*Rb*Ra*Rb*Rb;
AR10=Rb*Ra*Rb*Ra*Rb*Rb*Ra;
AR11=Rb*Ra*Rb*Ra*Rb*Rb*Ra*Rb*Ra;
AR12=Rb*Ra*Rb*Ra*Rb*Rb*Ra*Rb;
AAR={AR1 AR2 AR3 AR4 AR5 AR6 AR7 AR8 AR9 AR10 AR11 AR12};
Rc=Ra*Rb;

alter=[];
altermatri=cell(60,1);
alterot=cell(60,1);
for i=1:12
    for j=0:4
        list=(c)^j*AA{i}*[1:12]';
        alter=[alter,list];
        altermatri{5*(i-1)+j+1}=(c)^j*AA{i};
        alterot{5*(i-1)+j+1}=(Rc)^j*AAR{i};
    end
end

the third output is rotation matrix, the configuration based on the initial point.

Thank you  for your interest, we will release the code before the conference.

**Comment by xuyinxuyin** [comment]
```
function [alter,altermatri,alterot]=alter52()
a=zeros(12,12);
a(1,7)=1;
a(2,11)=1;
a(3,12)=1;
a(4,5)=1;
a(5,4)=1;
a(6,8)=1;
a(7,1)=1;
a(8,6)=1;
a(9,10)=1;
a(10,9)=1;
a(11,2)=1;
a(12,3)=1;
blist=[2,7,6,5,10,11,1,9,12,4,3,8];
b=zeros(12,12);
for i=1:12
    b(i,blist(i))=1;
end
[Ra,Rb]=rotation();
A1=eye(12,12);
A2=a;
A3=b;
A4=b*a;
A5=b*a*b;
A6=b*a*b*a*b;
A7=b*a*b*a;
A8=b*a*b*a*b*a;
A9=b*a*b*a*b*b;
A10=b*a*b*a*b*b*a;
A11=b*a*b*a*b*b*a*b*a;
A12=b*a*b*a*b*b*a*b;
AA={A1 A2 A3 A4 A5 A6 A7 A8 A9 A10 A11 A12};
c=a*b;

AR1=eye(3,3);
AR2=Ra;
AR3=Rb;
AR4=Rb*Ra;
AR5=Rb*Ra*Rb;
AR6=Rb*Ra*Rb*Ra*Rb;
AR7=Rb*Ra*Rb*Ra;
AR8=Rb*Ra*Rb*Ra*Rb*Ra;
AR9=Rb*Ra*Rb*Ra*Rb*Rb;
AR10=Rb*Ra*Rb*Ra*Rb*Rb*Ra;
AR11=Rb*Ra*Rb*Ra*Rb*Rb*Ra*Rb*Ra;
AR12=Rb*Ra*Rb*Ra*Rb*Rb*Ra*Rb;
AAR={AR1 AR2 AR3 AR4 AR5 AR6 AR7 AR8 AR9 AR10 AR11 AR12};
Rc=Ra*Rb;

alter=[];
altermatri=cell(60,1);
alterot=cell(60,1);
for i=1:12
    for j=0:4
        list=(c)^j*AA{i}*[1:12]';
        alter=[alter,list];
        altermatri{5*(i-1)+j+1}=(c)^j*AA{i};
        alterot{5*(i-1)+j+1}=(Rc)^j*AAR{i};
    end
end
```
here is the code for rotation matrix, the configurations are based on initial points.
Thank you for your interest, we will release the code before the conference

**Comment by YoungXIAO13** [comment]
Thanks for your reply!
